id: PDCF00390
initial_creation_type: ocr
source_metadata:
  volumes:
    6619bbb790c34cc7b65cf612b974bffc:
      base_file: v120.txt
      image_group_id: I1PD95965
      title: དབང་ཕྱུག་བྱེད་པ་པོ་ཉིད་སེལ་བ་དང་ཁྱབ་འཇུག་བྱེད་པ་པོ་གཅིག་ཉིད་སེལ་བར་བྱེད་པ།
      total_pages: 1865
      volume_number: 120
